services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_PASSWORD}
      MYSQL_DATABASE: ${ENV_USER}
    command: --explicit_defaults_for_timestamp
    volumes:
      - dbdata:/var/lib/mysql
      
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:8.1.7-apache
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_SERVER: db
      DB_NAME: ${ENV_USER}
      DB_USER: ${ENV_DBUSER}
      DB_PASSWD: ${ENV_PASSWORD}
      PS_DOMAIN: ${ENV_DOMAIN}
      PS_FOLDER_ADMIN: adminbehh501
      PS_COUNTRY: fr
      ADMIN_MAIL: ${ENV_ADMIN_MAIL}
      ADMIN_PASSWD: ${ENV_ADMIN_PASSWD}
      PS_INSTALL_AUTO: 1
    # command: bash -c "chown -R www-data:www-data /var/www/html/"
    volumes:
      - psdata:/var/www/html
      - ./html/themes/classic:/var/www/html/themes/classic
      - ./html/themes/themenfant_BEHH:/var/www/html/themes/themenfant_BEHH
      - ./html/modules:/var/www/html/modules
      - ./html/controllers/front:/var/www/html/controllers/front

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: mmi

volumes:
  dbdata:
  psdata:
